### ISSUE TITLE
move(:bottom) results in 'wrong number of arguments'  - mongoid 3.1.2

### ISSUE THREAD

**Issue by oma** [kristianmandrup/acts_as_list_mongoid#10]
ruby-1.9.3-p385
mongoid-3.1.2
mongodb version v2.4.0

_embedded documents_

move(:top) works

```
# document 'doc' has many embedded documents 'eds'
e = doc.eds.last
e.move(:top)
d.eds.map(&:position)
   => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 1] 
doc.reload
doc.eds.map(&:position)
   => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] 
```

move(:bottom) crashes

```
doc.eds.map(&:position)
   => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] 
e = doc.eds.first
e.move(:bottom)
# fails. see stacktrace below.
doc.eds.map(&:position)
   => [1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] 
```

Stacktrace 

```
ArgumentError: wrong number of arguments (0 for 1)
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/mongoid-3.1.2/lib/mongoid/contextual/memory.rb:225:in `sort'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/mongoid-3.1.2/lib/mongoid/contextual.rb:19:in `sort'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/acts_as_list_mongoid-0.2.5.1/lib/mongoid/acts_as_list.rb:107:in `order_by_position'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/acts_as_list_mongoid-0.2.5.1/lib/mongoid/acts_as_list.rb:304:in `bottom_item'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/acts_as_list_mongoid-0.2.5.1/lib/mongoid/acts_as_list.rb:293:in `bottom_position_in_list'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/acts_as_list_mongoid-0.2.5.1/lib/mongoid/acts_as_list.rb:309:in `assume_bottom_position'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/acts_as_list_mongoid-0.2.5.1/lib/mongoid/acts_as_list.rb:193:in `move_to_bottom'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/acts_as_list_mongoid-0.2.5.1/lib/mongoid/acts_as_list.rb:77:in `move'
from (irb):51
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
from /Users/oma/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by kristianmandrup** [comment]
Looks like the error is in `acts_as_list.rb:107:in`order_by_position'``
Try running the specs. I think the last time I ran the specs on this gem was well before mongoid`3.0`.
See the code for`move :top` that works and then examine the difference for move :bottom.
Fix it... then make a pull request ;)
Thanks!

**Comment by oma** [comment]
You cannot use this gem for mongoid versions prior to 3.0.0 and specs haven't been run for >=3.0? Who's actively maintaining this lib? I was just playing around with this gem in rails console to see if it would do the trick. I may create a pull request if I decide to use this gem, but I might go for mongoid_orderable. Just being honest, I appreciate all the efforts you've all put into this. Thanks
